apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitops-repo-pruner
spec:
  schedule: "0 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: gitops-repo-pruner
          containers:
          - name: hello
            image: gitops-repo-pruner:latest
            imagePullPolicy: Always
            command:
            - ./entrypoint.sh
          restartPolicy: Never